[package]
name = "math_lmp"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies]
candle-core = "0.3"
candle-nn = "0.3"
candle-transformers = "0.3"
tokenizers = "0.15.2"
anyhow = "1.0"
rand = "0.8"
